from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class SettingsRepositoryProtocol(Protocol):
    def load(self) -> Any: ...
    def save(self, settings: Any) -> None: ...


@runtime_checkable
class ImageRepositoryProtocol(Protocol):
    def list_images(self, directory: str) -> List[str]: ...
    def validate_path(self, path: str) -> Optional[str]: ...


@runtime_checkable
class CacheRepositoryProtocol(Protocol):
    def get_thumbnail_path(self, image_path: str) -> Optional[str]: ...
    def save_thumbnail(self, image_path: str, data: bytes) -> str: ...
    def clear(self) -> None: ...
