from __future__ import annotations

from typing import Any, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class PipelineServiceProtocol(Protocol):
    def start(self, paths: List[str], settings: Any, output_folder: str) -> None: ...
    def cancel(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...


@runtime_checkable
class ExportServiceProtocol(Protocol):
    def export(self, source_paths: List[str], output_dir: str) -> int: ...


@runtime_checkable
class ImageServiceProtocol(Protocol):
    def add(self, paths: List[str]) -> List[str]: ...
    def remove(self, paths: List[str]) -> None: ...
